services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start:prod
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
      - localstack
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/hubxp-test
      - S3_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - S3_BUCKET=products-images
    depends_on:
      - mongodb
      - localstack

volumes:
  mongodb_data:
